/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum ChannelErrCode
{
  chOK = 0,
  chNotExist = -1,
  chModifing = -2,
  chDeleting = -3,
  camClosed = -4,
  camRebooting = -5,
  camIpErr = -6,
  camLogonErr = -7,
  camURLErr = -8,
  faceCapErr = -9,
}
