/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class CmpServerFaceObj : TBase
{
  private string _faceObjID;
  private List<FaceTemplate> _ft;

  public string FaceObjID
  {
    get
    {
      return _faceObjID;
    }
    set
    {
      __isset.faceObjID = true;
      this._faceObjID = value;
    }
  }

  public List<FaceTemplate> Ft
  {
    get
    {
      return _ft;
    }
    set
    {
      __isset.ft = true;
      this._ft = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool faceObjID;
    public bool ft;
  }

  public CmpServerFaceObj() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              FaceObjID = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                Ft = new List<FaceTemplate>();
                TList _list8 = iprot.ReadListBegin();
                for( int _i9 = 0; _i9 < _list8.Count; ++_i9)
                {
                  FaceTemplate _elem10;
                  _elem10 = new FaceTemplate();
                  _elem10.Read(iprot);
                  Ft.Add(_elem10);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("CmpServerFaceObj");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (FaceObjID != null && __isset.faceObjID) {
        field.Name = "faceObjID";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(FaceObjID);
        oprot.WriteFieldEnd();
      }
      if (Ft != null && __isset.ft) {
        field.Name = "ft";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Ft.Count));
          foreach (FaceTemplate _iter11 in Ft)
          {
            _iter11.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("CmpServerFaceObj(");
    bool __first = true;
    if (FaceObjID != null && __isset.faceObjID) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("FaceObjID: ");
      __sb.Append(FaceObjID);
    }
    if (Ft != null && __isset.ft) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Ft: ");
      __sb.Append(Ft);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

