/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class UserCfg : TBase
{
  private string _uid;
  private string _uname;
  private string _upwd;
  private string _utype;
  private string _div_index;
  private string _div_order;

  public string Uid
  {
    get
    {
      return _uid;
    }
    set
    {
      __isset.uid = true;
      this._uid = value;
    }
  }

  public string Uname
  {
    get
    {
      return _uname;
    }
    set
    {
      __isset.uname = true;
      this._uname = value;
    }
  }

  public string Upwd
  {
    get
    {
      return _upwd;
    }
    set
    {
      __isset.upwd = true;
      this._upwd = value;
    }
  }

  public string Utype
  {
    get
    {
      return _utype;
    }
    set
    {
      __isset.utype = true;
      this._utype = value;
    }
  }

  public string Div_index
  {
    get
    {
      return _div_index;
    }
    set
    {
      __isset.div_index = true;
      this._div_index = value;
    }
  }

  public string Div_order
  {
    get
    {
      return _div_order;
    }
    set
    {
      __isset.div_order = true;
      this._div_order = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool uid;
    public bool uname;
    public bool upwd;
    public bool utype;
    public bool div_index;
    public bool div_order;
  }

  public UserCfg() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Uid = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Uname = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              Upwd = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              Utype = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              Div_index = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.String) {
              Div_order = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("UserCfg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Uid != null && __isset.uid) {
        field.Name = "uid";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Uid);
        oprot.WriteFieldEnd();
      }
      if (Uname != null && __isset.uname) {
        field.Name = "uname";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Uname);
        oprot.WriteFieldEnd();
      }
      if (Upwd != null && __isset.upwd) {
        field.Name = "upwd";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Upwd);
        oprot.WriteFieldEnd();
      }
      if (Utype != null && __isset.utype) {
        field.Name = "utype";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Utype);
        oprot.WriteFieldEnd();
      }
      if (Div_index != null && __isset.div_index) {
        field.Name = "div_index";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Div_index);
        oprot.WriteFieldEnd();
      }
      if (Div_order != null && __isset.div_order) {
        field.Name = "div_order";
        field.Type = TType.String;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Div_order);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("UserCfg(");
    bool __first = true;
    if (Uid != null && __isset.uid) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Uid: ");
      __sb.Append(Uid);
    }
    if (Uname != null && __isset.uname) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Uname: ");
      __sb.Append(Uname);
    }
    if (Upwd != null && __isset.upwd) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Upwd: ");
      __sb.Append(Upwd);
    }
    if (Utype != null && __isset.utype) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Utype: ");
      __sb.Append(Utype);
    }
    if (Div_index != null && __isset.div_index) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Div_index: ");
      __sb.Append(Div_index);
    }
    if (Div_order != null && __isset.div_order) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Div_order: ");
      __sb.Append(Div_order);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

