/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class NotifyCfg : TBase
{
  private int _itemcode;
  private string _itemstr;

  public int Itemcode
  {
    get
    {
      return _itemcode;
    }
    set
    {
      __isset.itemcode = true;
      this._itemcode = value;
    }
  }

  public string Itemstr
  {
    get
    {
      return _itemstr;
    }
    set
    {
      __isset.itemstr = true;
      this._itemstr = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool itemcode;
    public bool itemstr;
  }

  public NotifyCfg() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Itemcode = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Itemstr = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("NotifyCfg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.itemcode) {
        field.Name = "itemcode";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Itemcode);
        oprot.WriteFieldEnd();
      }
      if (Itemstr != null && __isset.itemstr) {
        field.Name = "itemstr";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Itemstr);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("NotifyCfg(");
    bool __first = true;
    if (__isset.itemcode) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Itemcode: ");
      __sb.Append(Itemcode);
    }
    if (Itemstr != null && __isset.itemstr) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Itemstr: ");
      __sb.Append(Itemstr);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

