/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

public partial class UIServer {
  public interface Iface {
    int UpdateRealtimeCap(RealtimeCapInfo info, string channelname);
    #if SILVERLIGHT
    IAsyncResult Begin_UpdateRealtimeCap(AsyncCallback callback, object state, RealtimeCapInfo info, string channelname);
    int End_UpdateRealtimeCap(IAsyncResult asyncResult);
    #endif
    int UpdateRealtimeCmp(RealtimeCmpInfo info, string channelname);
    #if SILVERLIGHT
    IAsyncResult Begin_UpdateRealtimeCmp(AsyncCallback callback, object state, RealtimeCmpInfo info, string channelname);
    int End_UpdateRealtimeCmp(IAsyncResult asyncResult);
    #endif
  }

  public class Client : IDisposable, Iface {
    public Client(TProtocol prot) : this(prot, prot)
    {
    }

    public Client(TProtocol iprot, TProtocol oprot)
    {
      iprot_ = iprot;
      oprot_ = oprot;
    }

    protected TProtocol iprot_;
    protected TProtocol oprot_;
    protected int seqid_;

    public TProtocol InputProtocol
    {
      get { return iprot_; }
    }
    public TProtocol OutputProtocol
    {
      get { return oprot_; }
    }


    #region " IDisposable Support "
    private bool _IsDisposed;

    // IDisposable
    public void Dispose()
    {
      Dispose(true);
    }
    

    protected virtual void Dispose(bool disposing)
    {
      if (!_IsDisposed)
      {
        if (disposing)
        {
          if (iprot_ != null)
          {
            ((IDisposable)iprot_).Dispose();
          }
          if (oprot_ != null)
          {
            ((IDisposable)oprot_).Dispose();
          }
        }
      }
      _IsDisposed = true;
    }
    #endregion


    
    #if SILVERLIGHT
    public IAsyncResult Begin_UpdateRealtimeCap(AsyncCallback callback, object state, RealtimeCapInfo info, string channelname)
    {
      return send_UpdateRealtimeCap(callback, state, info, channelname);
    }

    public int End_UpdateRealtimeCap(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_UpdateRealtimeCap();
    }

    #endif

    public int UpdateRealtimeCap(RealtimeCapInfo info, string channelname)
    {
      #if !SILVERLIGHT
      send_UpdateRealtimeCap(info, channelname);
      return recv_UpdateRealtimeCap();

      #else
      var asyncResult = Begin_UpdateRealtimeCap(null, null, info, channelname);
      return End_UpdateRealtimeCap(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_UpdateRealtimeCap(AsyncCallback callback, object state, RealtimeCapInfo info, string channelname)
    #else
    public void send_UpdateRealtimeCap(RealtimeCapInfo info, string channelname)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("UpdateRealtimeCap", TMessageType.Call, seqid_));
      UpdateRealtimeCap_args args = new UpdateRealtimeCap_args();
      args.Info = info;
      args.Channelname = channelname;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public int recv_UpdateRealtimeCap()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      UpdateRealtimeCap_result result = new UpdateRealtimeCap_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.success) {
        return result.Success;
      }
      throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "UpdateRealtimeCap failed: unknown result");
    }

    
    #if SILVERLIGHT
    public IAsyncResult Begin_UpdateRealtimeCmp(AsyncCallback callback, object state, RealtimeCmpInfo info, string channelname)
    {
      return send_UpdateRealtimeCmp(callback, state, info, channelname);
    }

    public int End_UpdateRealtimeCmp(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_UpdateRealtimeCmp();
    }

    #endif

    public int UpdateRealtimeCmp(RealtimeCmpInfo info, string channelname)
    {
      #if !SILVERLIGHT
      send_UpdateRealtimeCmp(info, channelname);
      return recv_UpdateRealtimeCmp();

      #else
      var asyncResult = Begin_UpdateRealtimeCmp(null, null, info, channelname);
      return End_UpdateRealtimeCmp(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_UpdateRealtimeCmp(AsyncCallback callback, object state, RealtimeCmpInfo info, string channelname)
    #else
    public void send_UpdateRealtimeCmp(RealtimeCmpInfo info, string channelname)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("UpdateRealtimeCmp", TMessageType.Call, seqid_));
      UpdateRealtimeCmp_args args = new UpdateRealtimeCmp_args();
      args.Info = info;
      args.Channelname = channelname;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public int recv_UpdateRealtimeCmp()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      UpdateRealtimeCmp_result result = new UpdateRealtimeCmp_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.success) {
        return result.Success;
      }
      throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "UpdateRealtimeCmp failed: unknown result");
    }

  }
  public class Processor : TProcessor {
    public Processor(Iface iface)
    {
      iface_ = iface;
      processMap_["UpdateRealtimeCap"] = UpdateRealtimeCap_Process;
      processMap_["UpdateRealtimeCmp"] = UpdateRealtimeCmp_Process;
    }

    protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
    private Iface iface_;
    protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

    public bool Process(TProtocol iprot, TProtocol oprot)
    {
      try
      {
        TMessage msg = iprot.ReadMessageBegin();
        ProcessFunction fn;
        processMap_.TryGetValue(msg.Name, out fn);
        if (fn == null) {
          TProtocolUtil.Skip(iprot, TType.Struct);
          iprot.ReadMessageEnd();
          TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
          oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
          x.Write(oprot);
          oprot.WriteMessageEnd();
          oprot.Transport.Flush();
          return true;
        }
        fn(msg.SeqID, iprot, oprot);
      }
      catch (IOException)
      {
        return false;
      }
      return true;
    }

    public void UpdateRealtimeCap_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      UpdateRealtimeCap_args args = new UpdateRealtimeCap_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      UpdateRealtimeCap_result result = new UpdateRealtimeCap_result();
      result.Success = iface_.UpdateRealtimeCap(args.Info, args.Channelname);
      oprot.WriteMessageBegin(new TMessage("UpdateRealtimeCap", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

    public void UpdateRealtimeCmp_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      UpdateRealtimeCmp_args args = new UpdateRealtimeCmp_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      UpdateRealtimeCmp_result result = new UpdateRealtimeCmp_result();
      result.Success = iface_.UpdateRealtimeCmp(args.Info, args.Channelname);
      oprot.WriteMessageBegin(new TMessage("UpdateRealtimeCmp", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class UpdateRealtimeCap_args : TBase
  {
    private RealtimeCapInfo _info;
    private string _channelname;

    public RealtimeCapInfo Info
    {
      get
      {
        return _info;
      }
      set
      {
        __isset.info = true;
        this._info = value;
      }
    }

    public string Channelname
    {
      get
      {
        return _channelname;
      }
      set
      {
        __isset.channelname = true;
        this._channelname = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool info;
      public bool channelname;
    }

    public UpdateRealtimeCap_args() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Info = new RealtimeCapInfo();
                Info.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Channelname = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("UpdateRealtimeCap_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Info != null && __isset.info) {
          field.Name = "info";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Info.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Channelname != null && __isset.channelname) {
          field.Name = "channelname";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Channelname);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("UpdateRealtimeCap_args(");
      bool __first = true;
      if (Info != null && __isset.info) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Info: ");
        __sb.Append(Info== null ? "<null>" : Info.ToString());
      }
      if (Channelname != null && __isset.channelname) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Channelname: ");
        __sb.Append(Channelname);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class UpdateRealtimeCap_result : TBase
  {
    private int _success;

    public int Success
    {
      get
      {
        return _success;
      }
      set
      {
        __isset.success = true;
        this._success = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool success;
    }

    public UpdateRealtimeCap_result() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.I32) {
                Success = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("UpdateRealtimeCap_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          field.Name = "Success";
          field.Type = TType.I32;
          field.ID = 0;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Success);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("UpdateRealtimeCap_result(");
      bool __first = true;
      if (__isset.success) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Success: ");
        __sb.Append(Success);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class UpdateRealtimeCmp_args : TBase
  {
    private RealtimeCmpInfo _info;
    private string _channelname;

    public RealtimeCmpInfo Info
    {
      get
      {
        return _info;
      }
      set
      {
        __isset.info = true;
        this._info = value;
      }
    }

    public string Channelname
    {
      get
      {
        return _channelname;
      }
      set
      {
        __isset.channelname = true;
        this._channelname = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool info;
      public bool channelname;
    }

    public UpdateRealtimeCmp_args() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Info = new RealtimeCmpInfo();
                Info.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Channelname = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("UpdateRealtimeCmp_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Info != null && __isset.info) {
          field.Name = "info";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Info.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (Channelname != null && __isset.channelname) {
          field.Name = "channelname";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Channelname);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("UpdateRealtimeCmp_args(");
      bool __first = true;
      if (Info != null && __isset.info) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Info: ");
        __sb.Append(Info== null ? "<null>" : Info.ToString());
      }
      if (Channelname != null && __isset.channelname) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Channelname: ");
        __sb.Append(Channelname);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class UpdateRealtimeCmp_result : TBase
  {
    private int _success;

    public int Success
    {
      get
      {
        return _success;
      }
      set
      {
        __isset.success = true;
        this._success = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool success;
    }

    public UpdateRealtimeCmp_result() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.I32) {
                Success = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("UpdateRealtimeCmp_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          field.Name = "Success";
          field.Type = TType.I32;
          field.ID = 0;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Success);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("UpdateRealtimeCmp_result(");
      bool __first = true;
      if (__isset.success) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Success: ");
        __sb.Append(Success);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
